import { defineArrayMember, defineField, defineType } from "sanity";

export const contentPageType = defineType({
  name: "contentPage",
  title: "Content pagina",
  type: "document",
  fields: [
    defineField({
      name: "slug",
      title: "Pagina",
      type: "string",
      options: {
        list: [
          { title: "Verhuisdiensten", value: "verhuisdiensten" },
          { title: "Zakelijk verhuizen", value: "zakelijk-verhuizen" },
          { title: "Seniorenverhuizing", value: "seniorenverhuizing" },
          { title: "Spoedverhuizing", value: "spoedverhuizing" },
          { title: "Werkgebied", value: "werkgebied" },
          { title: "Over ons", value: "over-ons" },
          { title: "Contact", value: "contact" },
        ],
      },
      validation: (rule) => rule.required(),
    }),
    defineField({ name: "seoTitle", title: "SEO title", type: "string", validation: (rule) => rule.required().min(10).max(90) }),
    defineField({ name: "seoDescription", title: "SEO description", type: "text", rows: 3, validation: (rule) => rule.required().min(50).max(180) }),
    defineField({ name: "breadcrumb", title: "Breadcrumb label", type: "string", validation: (rule) => rule.required().min(2).max(60) }),
    defineField({ name: "introEyebrow", title: "Intro eyebrow", type: "string", validation: (rule) => rule.required().min(2).max(80) }),
    defineField({ name: "introTitle", title: "Intro titel", type: "string", validation: (rule) => rule.required().min(10).max(120) }),
    defineField({ name: "introDescription", title: "Intro tekst", type: "text", rows: 3, validation: (rule) => rule.required().min(20).max(320) }),
    defineField({ name: "galleryTitle", title: "Galerij titel", type: "string", validation: (rule) => rule.required().min(6).max(120) }),
    defineField({ name: "galleryDescription", title: "Galerij tekst", type: "text", rows: 3, validation: (rule) => rule.required().min(12).max(220) }),
    defineField({
      name: "galleryItems",
      title: "Galerij items",
      type: "array",
      of: [defineArrayMember({ type: "galleryItem" })],
      validation: (rule) => rule.required().min(3).max(6),
    }),
    defineField({ name: "featuresTitle", title: "Features titel", type: "string", validation: (rule) => rule.required().min(6).max(120) }),
    defineField({ name: "featuresDescription", title: "Features tekst", type: "text", rows: 3, validation: (rule) => rule.required().min(12).max(220) }),
    defineField({
      name: "features",
      title: "Features items",
      type: "array",
      of: [defineArrayMember({ type: "featureItem" })],
      validation: (rule) => rule.required().min(3).max(6),
    }),
    defineField({ name: "infoCardTitle", title: "Infoblok titel", type: "string", validation: (rule) => rule.required().min(4).max(120) }),
    defineField({ name: "infoCardText", title: "Infoblok tekst", type: "text", rows: 4, validation: (rule) => rule.required().min(20).max(800) }),
    defineField({
      name: "infoLinks",
      title: "Infoblok links",
      type: "array",
      of: [defineArrayMember({ type: "linkItem" })],
      validation: (rule) => rule.max(6),
    }),
    defineField({ name: "localProofTitle", title: "Lokale proof titel", type: "string", validation: (rule) => rule.required().min(6).max(120) }),
    defineField({ name: "localProofText", title: "Lokale proof tekst", type: "text", rows: 3, validation: (rule) => rule.required().min(12).max(260) }),
    defineField({ name: "showAreaSwitcher", title: "Toon area switcher", type: "boolean", initialValue: false }),
    defineField({ name: "showContactCard", title: "Toon contactkaart", type: "boolean", initialValue: false }),
    defineField({ name: "showContactForm", title: "Toon uitgebreid contactformulier", type: "boolean", initialValue: false }),
    defineField({ name: "faqTitle", title: "FAQ titel", type: "string", validation: (rule) => rule.required().min(6).max(120) }),
    defineField({
      name: "faqItems",
      title: "FAQ items",
      type: "array",
      of: [defineArrayMember({ type: "faqItem" })],
      validation: (rule) => rule.required().min(3).max(10),
    }),
    defineField({ name: "ctaTitle", title: "CTA titel", type: "string", validation: (rule) => rule.required().min(6).max(120) }),
    defineField({ name: "ctaText", title: "CTA tekst", type: "text", rows: 3, validation: (rule) => rule.required().min(12).max(260) }),
    defineField({ name: "jsonLdName", title: "Structured data naam", type: "string", validation: (rule) => rule.required().min(6).max(120) }),
    defineField({ name: "jsonLdDescription", title: "Structured data beschrijving", type: "text", rows: 3, validation: (rule) => rule.required().min(20).max(260) }),
  ],
  preview: {
    select: {
      title: "breadcrumb",
      subtitle: "slug",
    },
  },
});
