import { defineArrayMember, defineField, defineType } from "sanity";

export const homePageType = defineType({
  name: "homePage",
  title: "Homepage",
  type: "document",
  fields: [
    defineField({
      name: "title",
      title: "SEO title",
      type: "string",
      validation: (rule) => rule.required().min(10).max(90),
    }),
    defineField({
      name: "description",
      title: "SEO description",
      type: "text",
      rows: 3,
      validation: (rule) => rule.required().min(50).max(180),
    }),
    defineField({ name: "heroEyebrow", title: "Hero eyebrow", type: "string", validation: (rule) => rule.required().min(3).max(90) }),
    defineField({ name: "heroTitle", title: "Hero titel", type: "string", validation: (rule) => rule.required().min(10).max(120) }),
    defineField({ name: "heroSubtitle", title: "Hero subtitel", type: "text", rows: 3, validation: (rule) => rule.required().min(20).max(280) }),
    defineField({ name: "routeStartLabel", title: "Route label links", type: "string", validation: (rule) => rule.required().min(2).max(40) }),
    defineField({ name: "routeEndLabel", title: "Route label rechts", type: "string", validation: (rule) => rule.required().min(2).max(40) }),
    defineField({ name: "routeBoxOneLabel", title: "Route label kaart 1", type: "string", validation: (rule) => rule.required().min(2).max(40) }),
    defineField({ name: "routeBoxTwoLabel", title: "Route label kaart 2", type: "string", validation: (rule) => rule.required().min(2).max(40) }),
    defineField({ name: "routeStatOneValue", title: "Route stat 1 waarde", type: "string", validation: (rule) => rule.required().min(1).max(20) }),
    defineField({ name: "routeStatOneLabel", title: "Route stat 1 label", type: "string", validation: (rule) => rule.required().min(3).max(40) }),
    defineField({ name: "routeStatTwoValue", title: "Route stat 2 waarde", type: "string", validation: (rule) => rule.required().min(1).max(20) }),
    defineField({ name: "routeStatTwoLabel", title: "Route stat 2 label", type: "string", validation: (rule) => rule.required().min(3).max(40) }),
    defineField({ name: "movingGalleryTitle", title: "Galerij titel", type: "string", validation: (rule) => rule.required().min(6).max(120) }),
    defineField({ name: "movingGalleryDescription", title: "Galerij tekst", type: "text", rows: 3, validation: (rule) => rule.required().min(15).max(220) }),
    defineField({
      name: "movingGalleryItems",
      title: "Galerij items",
      type: "array",
      of: [defineArrayMember({ type: "galleryItem" })],
      validation: (rule) => rule.required().min(3).max(6),
    }),
    defineField({ name: "highlightsTitle", title: "Highlights titel", type: "string", validation: (rule) => rule.required().min(6).max(120) }),
    defineField({ name: "highlightsDescription", title: "Highlights tekst", type: "text", rows: 3, validation: (rule) => rule.required().min(15).max(220) }),
    defineField({
      name: "highlights",
      title: "Highlights",
      type: "array",
      of: [defineArrayMember({ type: "highlightItem" })],
      validation: (rule) => rule.required().min(3).max(4),
    }),
    defineField({ name: "metricsTitle", title: "Metrics titel", type: "string" }),
    defineField({
      name: "metrics",
      title: "Metrics",
      type: "array",
      of: [defineArrayMember({ type: "metricItem" })],
      validation: (rule) => rule.required().min(3).max(4),
    }),
    defineField({ name: "benefitsTitle", title: "Voordelen titel", type: "string", validation: (rule) => rule.required().min(6).max(120) }),
    defineField({ name: "benefitsDescription", title: "Voordelen tekst", type: "text", rows: 3, validation: (rule) => rule.required().min(15).max(240) }),
    defineField({
      name: "benefits",
      title: "Voordelen items",
      type: "array",
      of: [defineArrayMember({ type: "benefitItem" })],
      validation: (rule) => rule.required().min(4).max(6),
    }),
    defineField({ name: "localProofTitle", title: "Lokale proof titel", type: "string", validation: (rule) => rule.required().min(6).max(120) }),
    defineField({ name: "localProofText", title: "Lokale proof tekst", type: "text", rows: 3, validation: (rule) => rule.required().min(12).max(240) }),
    defineField({ name: "stepsTitle", title: "Stappen titel", type: "string", validation: (rule) => rule.required().min(6).max(120) }),
    defineField({ name: "stepsDescription", title: "Stappen tekst", type: "text", rows: 3, validation: (rule) => rule.required().min(12).max(200) }),
    defineField({
      name: "steps",
      title: "Stappen items",
      type: "array",
      of: [defineArrayMember({ type: "stepItem" })],
      validation: (rule) => rule.required().min(3).max(4),
    }),
    defineField({ name: "servicesTitle", title: "Diensten titel", type: "string", validation: (rule) => rule.required().min(6).max(120) }),
    defineField({ name: "servicesDescription", title: "Diensten tekst", type: "text", rows: 3, validation: (rule) => rule.required().min(12).max(200) }),
    defineField({
      name: "serviceCards",
      title: "Diensten kaarten",
      type: "array",
      of: [defineArrayMember({ type: "serviceCardItem" })],
      validation: (rule) => rule.required().min(4).max(6),
    }),
    defineField({ name: "servicesQuickFallback", title: "Fallback snelle tekst", type: "string", validation: (rule) => rule.required().min(5).max(120) }),
    defineField({ name: "showcaseTitle", title: "Showcase titel", type: "string", validation: (rule) => rule.required().min(6).max(120) }),
    defineField({ name: "showcaseDescription", title: "Showcase tekst", type: "text", rows: 3, validation: (rule) => rule.required().min(12).max(220) }),
    defineField({
      name: "showcaseItems",
      title: "Showcase items",
      type: "array",
      of: [defineArrayMember({ type: "galleryItem" })],
      validation: (rule) => rule.required().min(4).max(8),
    }),
    defineField({ name: "areasTitle", title: "Werkgebied titel", type: "string", validation: (rule) => rule.required().min(6).max(120) }),
    defineField({ name: "areasDescription", title: "Werkgebied tekst", type: "text", rows: 3, validation: (rule) => rule.required().min(12).max(220) }),
    defineField({
      name: "areas",
      title: "Werkgebied items",
      type: "array",
      of: [defineArrayMember({ type: "areaItem" })],
      validation: (rule) => rule.required().min(3).max(8),
    }),
    defineField({ name: "reviewsTitle", title: "Reviews titel", type: "string", validation: (rule) => rule.required().min(6).max(120) }),
    defineField({ name: "reviewsDescription", title: "Reviews tekst", type: "text", rows: 3, validation: (rule) => rule.required().min(12).max(220) }),
    defineField({ name: "reviewsScoreLabel", title: "Reviews score label", type: "string", validation: (rule) => rule.required().min(6).max(80) }),
    defineField({ name: "reviewsScoreText", title: "Reviews score tekst", type: "string", validation: (rule) => rule.required().min(6).max(120) }),
    defineField({ name: "faqTitle", title: "FAQ titel", type: "string", validation: (rule) => rule.required().min(6).max(120) }),
    defineField({
      name: "faqItems",
      title: "FAQ items",
      type: "array",
      of: [defineArrayMember({ type: "faqItem" })],
      validation: (rule) => rule.required().min(3).max(8),
    }),
    defineField({ name: "ctaTitle", title: "CTA titel", type: "string", validation: (rule) => rule.required().min(6).max(120) }),
    defineField({ name: "ctaText", title: "CTA tekst", type: "text", rows: 3, validation: (rule) => rule.required().min(12).max(240) }),
  ],
});
